### ISSUE TITLE
ranger相关工作

### ISSUE THREAD

**Issue by mdianjun** [cloudnativecube/reference#2]
1. Ranger的UserSync的工作模式，如何同步Unix/LDAP用户
2. Kerberos认证如何与Ranger的授权对接
3. Ranger支持KMS策略密钥管理，探究一下它的工作原理
4. 关于审计数据管理，能否用ElasticsSearch代替Solr

**Comment by XiongxinZ** [comment]
关于审计数据管理，能否用ElasticsSearch代替Solr？可以替代，现在ranger支持es作为审计db，在配置文件中添加修改并添加相应配置:
audit_elasticsearch_urls=
audit_elasticsearch_port=
audit_elasticsearch_protocol=
audit_elasticsearch_user=
audit_elasticsearch_password=
audit_elasticsearch_index=
audit_elasticsearch_boostrap_enabled=true
关于Kerberos认证如何与Ranger的授权对接：在ranger添加kerberos服务，创建相应的policy，将生成的 keytab文件拷贝到 hadoop 集群的机器 并修改权限 进行操作，详情参考：https://blog.csdn.net/qq_35995514/article/details/106575381 中的2.1

**Comment by XiongxinZ** [comment]
May 08, 2021 10:07:36 AM org.apache.ranger.server.tomcat.EmbeddedServer getKeyManagers
WARNING: Unable to read credential from credential store file [/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp/WEB-INF/classes/conf/.jceks/rangeradmin.jceks] for given alias:keyStoreCredentialAlias
May 08, 2021 10:07:36 AM org.apache.ranger.server.tomcat.EmbeddedServer getTrustManagers
WARNING: Config 'ranger.truststore.file' is not found or contains blank value!
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer start
INFO: Deriving webapp folder from catalina.base property. folder=/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer start
INFO: Webapp file =/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp, webAppName = /
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer start
INFO: Adding webapp [/] = path [/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp] .....
May 08, 2021 10:07:37 AM org.apache.catalina.core.StandardContext setPath
WARNING: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
May 08, 2021 10:07:37 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Context/JarScanner} Setting property 'scanManifest' to 'false' did not find a matching property.
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer start
INFO: Finished init of webapp [/] = path [/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp].
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer start
INFO: Name is empty. Setting Name Rule as 'DEFAULT'
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.EmbeddedServer startServer
INFO: Server Name : rangeradmin
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper <init>
INFO: Starting Ranger audit schema setup in ElasticSearch.
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper run
INFO: Started run method
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper run
INFO: Elastic search hosts=http://127.0.0.1:6080, index=ranger_audits
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper run
INFO: Trying to acquire elastic search connection
May 08, 2021 10:07:37 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-6080"]
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper getRestClientBuilder
SEVERE: ElasticSearch Credentials not provided!!
May 08, 2021 10:07:37 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
May 08, 2021 10:07:37 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.105
May 08, 2021 10:07:37 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp/WEB-INF/lib/javax.servlet-api-3.1.0.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
May 08, 2021 10:07:37 AM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
INFO: validateJarFile(/Users/xiongxinzeng/apache-project/ranger/target/ranger-3.0.0-SNAPSHOT-admin/ews/webapp/WEB-INF/lib/tomcat-el-api-8.5.63.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
May 08, 2021 10:07:37 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper run
INFO: Connection to elastic search established successfully
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper createIndex
INFO: Index ranger_audits not available.
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper createIndex
INFO: Index does not exist. Attempting to create index:ranger_audits
May 08, 2021 10:07:37 AM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: urn:com:sun:jersey:api:view is already defined
May 08, 2021 10:07:37 AM org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper createIndex
SEVERE: Unable to create Index. Reason:java.io.IOException: http://127.0.0.1:6080
java.io.IOException: http://127.0.0.1:6080
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1514)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1499)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1466)
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:132)
	at org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper.createIndex(ElasticSearchIndexBootStrapper.java:257)
	at org.apache.ranger.server.tomcat.ElasticSearchIndexBootStrapper.run(ElasticSearchIndexBootStrapper.java:147)
Caused by: java.net.UnknownHostException: http://127.0.0.1:6080
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:244)
	... 7 more
